import LoginCompo from "@/components/ui/loginCompo";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "UM/Login",
  description: "Generated by create next app",
};

const Login = () => {
  return <LoginCompo />;
};

export default Login;
